// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZGkxNDgevyTxtaECzypcZFrnXQEArV0',
    appId: '1:635604110866:web:1a7816c97adb75c0a192cb',
    messagingSenderId: '635604110866',
    projectId: 'clair-52652',
    authDomain: 'clair-52652.firebaseapp.com',
    databaseURL: 'https://clair-52652.firebaseio.com',
    storageBucket: 'clair-52652.appspot.com',
    measurementId: 'G-CSEQQ8NLRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqAxwbuxkB1YsSikehL8MKrxr2f5DFAkQ',
    appId: '1:635604110866:android:dd1cb1947da04b0d',
    messagingSenderId: '635604110866',
    projectId: 'clair-52652',
    databaseURL: 'https://clair-52652.firebaseio.com',
    storageBucket: 'clair-52652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIl3NbizAI6AIxxNRp6-0IKKa_XBMvCzk',
    appId: '1:635604110866:ios:9dfcfe653ced6229a192cb',
    messagingSenderId: '635604110866',
    projectId: 'clair-52652',
    databaseURL: 'https://clair-52652.firebaseio.com',
    storageBucket: 'clair-52652.appspot.com',
    androidClientId: '635604110866-2k1ev1fu7836plqol8vi07cqvogu5ovv.apps.googleusercontent.com',
    iosClientId: '635604110866-aekav1frdndo6usmt59n0fh4mtco6qov.apps.googleusercontent.com',
    iosBundleId: 'com.socialfaculty.claire',
  );
}
